In packaging scripts, sources and build directories are separated

diff --git a/pack/deb/make-deb-pkg b/pack/deb/make-deb-pkg
--- a/pack/deb/make-deb-pkg
+++ b/pack/deb/make-deb-pkg
@@ -26,7 +26,11 @@ CTL_FIlE=./${PKG_NAME}/DEBIAN/control
 
 # Make bin image
 cd ../..
-./pack/make-bin-image . ./${PKG_NAME} ${QT_MAJV}
+./pack/make-bin-image . . ./${PKG_NAME} ${QT_MAJV}
+if [ $? -ne 0 ]; then
+  echo "make-bin-image failed!"
+  exit 1
+fi
 # Copy debianization template
 cp -R ./pack/deb/DEBIAN ./${PKG_NAME}/
 # Add version number and arch to control file
diff --git a/pack/rpm/make-rpm-pkg b/pack/rpm/make-rpm-pkg
--- a/pack/rpm/make-rpm-pkg
+++ b/pack/rpm/make-rpm-pkg
@@ -14,6 +14,10 @@ fi
 PKG_NAME=doublecontact_${DC_VER}_amd64
 
 # cd .
-../make-bin-image ../.. ../../${PKG_NAME} ${QT_MAJV}
+../make-bin-image ../.. ../.. ../../${PKG_NAME} ${QT_MAJV}
+if [ $? -ne 0 ]; then
+  echo "make-bin-image failed!"
+  exit 1
+fi
 # TODO change version number and arch in control file
 rpmbuild -bb --buildroot `pwd`/../../${PKG_NAME} ./doublecontact.spec
diff --git a/pack/txz/make-txz-pkg b/pack/txz/make-txz-pkg
--- a/pack/txz/make-txz-pkg
+++ b/pack/txz/make-txz-pkg
@@ -14,7 +14,11 @@ fi
 PKG_NAME=doublecontact_${DC_VER}_amd64
 
 # cd .
-../make-bin-image ../.. ../../${PKG_NAME} ${QT_MAJV}
-cp ./remove-doublecontact-root-build ../../${PKG_NAME}/
-tar -cJf ../../${PKG_NAME}.tar.xz `pwd`/../../${PKG_NAME}
+../make-bin-image ../.. ../../../build-stat ../../../${PKG_NAME} ${QT_MAJV}
+if [ $? -ne 0 ]; then
+  echo "make-bin-image failed!"
+  exit 1
+fi
+cp ./remove-doublecontact-root-build ../../../${PKG_NAME}/
+tar -cJf ../../../${PKG_NAME}.tar.xz `pwd`/../../../${PKG_NAME}
 
